Fix coffelint error causing Travis builds to fail
Currently, running coffeelint produces this error and causes Travis
builds to fail:

```
Running "coffeelint:src" (coffeelint) task
src/command-installer.coffee
  ✖  line 73  Line contains inconsistent indentation  Expected 2 got 0
✖ 1 error
Warning: Task "coffeelint:src" failed. Use --force to continue.
Error: Task "coffeelint:src" failed.
```

See https://github.com/clutchski/coffeelint/issues/189 for more information
on this problem and suggested approach, and for a different place in Atom
where this approach is used see this:

https://github.com/atom/atom/blob/8242dfe38c9a6461eb4b4a9f97c25371b6e4d5a1/src/config.coffee#L984